### ISSUE TITLE
Вы забыли открыть пулл-реквест

### ISSUE THREAD

**Issue by alexander-litvinovich** [MoMentalochka/MessageForm#1]
@MoMentalochka 
Откройте пулл-реквест и сделайте так, чтобы в «Files changed» были все файлы.
Я могу это сделать за вас, но это будет жирнейшим и длиннейшим минусом.

**Comment by MoMentalochka** [comment]
Я озадачен, изначально не делил проект на ветки, писал в мастер и вот под конец добавил собранную версию, если чество довольно непонятная задача, куда мне на таком этапе переливаться и зачем ?
